import type { Locale } from "@/i18n/config";

/** Interface copy of the growth case study template; the case study itself comes from Sanity. */
const fr = {
  back: "Tous les projets",
  brief: "La campagne en bref",
  briefTitle: "L'essentiel en *10 secondes*",
  sector: "Secteur",
  services: "Ce que nous avons fait",
  channels: "Canaux",
  tools: "Outils",
  team: "L'équipe TechFlow",
  visit: "Voir le site",
  related: "D'autres projets",
  photos: "Photos",
  seeAds: "Voir les publicités",
  video: "Vidéo",
  watch: "Regarder",
  watchVideo: (n: number, angle: string) => `Regarder la vidéo ${n} : ${angle}`,
  platform: "Plateforme",
  asPublished: "Publiée",
  platforms: { instagram: "Instagram", facebook: "Facebook", tiktok: "TikTok" },
  sponsored: "Sponsorisé",
  follow: "Suivre",
  reels: "Reels",
  forYou: "Pour toi",
  following: "Abonnements",
  close: "Fermer",
  play: "Lecture",
  pause: "Pause",
  mute: "Couper le son",
  unmute: "Activer le son",
  previous: "Vidéo précédente",
  next: "Vidéo suivante",
  seek: "Position dans la vidéo",
  script: "Structure du script",
  tested: "Ce qu'elle teste",
  stage: "Étape",
  stagePrev: "Étape précédente",
  stageNext: "Étape suivante",
  measuredBy: "Indicateur",
  seeHow: "Voir comment",
  storyboard: "Storyboard",
  hooks: "Les accroches",
  week: "Semaine",
  budgetShare: "Part du budget",
  costPerLead: "Coût par lead relatif",
  winner: "gagnante",
  testing: "en test",
  paused: "coupée",
  illustrative: "Exemple illustratif",
  budgetOverTime: "Répartition du budget, semaine par semaine",
  scoring: "Scoring en temps réel",
  source: "Source",
  interest: "Intérêt",
  tiers: { hot: "Chaud", warm: "Tiède", cold: "Froid" },
  salesTeam: "Équipe commerciale",
  postsPerWeek: (n: number) => `${n} posts / semaine`,
  everyComment: "Chaque commentaire reçoit une réponse",
  typicalWeek: "Semaine type",
  days: { mon: "Lun", tue: "Mar", wed: "Mer", thu: "Jeu", fri: "Ven", sat: "Sam", sun: "Dim" },
  posts: "publications",
  comments: "Commentaires",
  author: "Auteur",
  typing: (handle: string) => `${handle} est en train d'écrire…`,
  addComment: "Ajouter un commentaire…",
  exampleThread: "Exemple d'échanges modérés par notre équipe",
  results: "Résultats",
  tracked: "Mesuré chaque semaine",
  inProgress: "Campagne en cours : les chiffres seront publiés à la fin du premier cycle.",
  included: "Inclus",
  quote: "Demander un devis",
  nextCase: "Étude de cas suivante",
  sourceLink: "Source",
};

const en: typeof fr = {
  back: "All projects",
  brief: "The campaign at a glance",
  briefTitle: "The essentials in *10 seconds*",
  sector: "Sector",
  services: "What we did",
  channels: "Channels",
  tools: "Tools",
  team: "The TechFlow team",
  visit: "Visit the site",
  related: "More projects",
  photos: "Photos",
  seeAds: "Watch the ads",
  video: "Video",
  watch: "Watch",
  watchVideo: (n, angle) => `Watch video ${n}: ${angle}`,
  platform: "Platform",
  asPublished: "As run",
  platforms: { instagram: "Instagram", facebook: "Facebook", tiktok: "TikTok" },
  sponsored: "Sponsored",
  follow: "Follow",
  reels: "Reels",
  forYou: "For You",
  following: "Following",
  close: "Close",
  play: "Play",
  pause: "Pause",
  mute: "Mute",
  unmute: "Unmute",
  previous: "Previous video",
  next: "Next video",
  seek: "Video position",
  script: "Script structure",
  tested: "What it tests",
  stage: "Stage",
  stagePrev: "Previous stage",
  stageNext: "Next stage",
  measuredBy: "Measured by",
  seeHow: "See how",
  storyboard: "Storyboard",
  hooks: "The hooks",
  week: "Week",
  budgetShare: "Budget share",
  costPerLead: "Relative cost per lead",
  winner: "winner",
  testing: "testing",
  paused: "paused",
  illustrative: "Illustrative example",
  budgetOverTime: "Budget split, week by week",
  scoring: "Live scoring",
  source: "Source",
  interest: "Interest",
  tiers: { hot: "Hot", warm: "Warm", cold: "Cold" },
  salesTeam: "Sales team",
  postsPerWeek: (n) => `${n} posts / week`,
  everyComment: "Every comment gets a reply",
  typicalWeek: "Typical week",
  days: { mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun" },
  posts: "posts",
  comments: "Comments",
  author: "Author",
  typing: (handle) => `${handle} is typing…`,
  addComment: "Add a comment…",
  exampleThread: "Example of conversations moderated by our team",
  results: "Results",
  tracked: "Measured every week",
  inProgress: "Campaign live: figures will be published at the end of the first cycle.",
  included: "Included",
  quote: "Get a quote",
  nextCase: "Next case study",
  sourceLink: "Source",
};

export const growthCopy: Record<Locale, typeof fr> = { fr, en };
export type DayKey = keyof typeof fr.days;
