import type { Locale } from "@/i18n/config";

/** Interface copy of the growth case study template; the case study itself comes from Sanity. */
const fr = {
  back: "Tous les projets",
  brief: "La campagne en bref",
  briefTitle: "L'essentiel en *10 secondes*",
  sector: "Secteur",
  services: "Ce que nous avons fait",
  channels: "Canaux",
  tools: "Outils",
  team: "L'équipe TechFlow",
  reading: "Lecture",
  minutes: "min",
  visit: "Voir le site",
  related: "D'autres projets",
  quote: "Demander un devis",
  seeAds: "Voir les publicités",
  video: "Vidéo",
  watch: "Regarder",
  watchVideo: (n: number, angle: string) => `Regarder la vidéo ${n} : ${angle}`,
  platform: "Plateforme",
  asPublished: "Publiée",
  platforms: { instagram: "Instagram", facebook: "Facebook", tiktok: "TikTok" },
  sponsored: "Sponsorisé",
  follow: "Suivre",
  reels: "Reels",
  forYou: "Pour toi",
  following: "Abonnements",
  close: "Fermer",
  play: "Lecture",
  pause: "Pause",
  mute: "Couper le son",
  unmute: "Activer le son",
  previous: "Vidéo précédente",
  next: "Vidéo suivante",
  seek: "Position dans la vidéo",
  tested: "Ce qu'elle teste",
};

const en: typeof fr = {
  back: "All projects",
  brief: "The campaign at a glance",
  briefTitle: "The essentials in *10 seconds*",
  sector: "Sector",
  services: "What we did",
  channels: "Channels",
  tools: "Tools",
  team: "The TechFlow team",
  reading: "Reading",
  minutes: "min",
  visit: "Visit the site",
  related: "More projects",
  quote: "Get a quote",
  seeAds: "Watch the ads",
  video: "Video",
  watch: "Watch",
  watchVideo: (n, angle) => `Watch video ${n}: ${angle}`,
  platform: "Platform",
  asPublished: "As run",
  platforms: { instagram: "Instagram", facebook: "Facebook", tiktok: "TikTok" },
  sponsored: "Sponsored",
  follow: "Follow",
  reels: "Reels",
  forYou: "For You",
  following: "Following",
  close: "Close",
  play: "Play",
  pause: "Pause",
  mute: "Mute",
  unmute: "Unmute",
  previous: "Previous video",
  next: "Next video",
  seek: "Video position",
  tested: "What it tests",
};

export const growthCopy: Record<Locale, typeof fr> = { fr, en };
