/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Benefit = {
  _type: "benefit";
  title?: string;
  text?: string;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Metric = {
  _type: "metric";
  value?: string;
  label?: string;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Table)
>;

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ToolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tool";
};

export type InsightReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "insight";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: ProjectReference | ToolReference | InsightReference;
  language?: string;
};

export type Insight = {
  _id: string;
  _type: "insight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  categories?: Array<string>;
  publishedAt?: string;
  author?: string;
  coverImage?: ImageWithAlt;
  body?: BlockContent;
  seo?: Seo;
  sourceUrl?: string;
};

export type Tool = {
  _id: string;
  _type: "tool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  intro?: string;
  benefitsTitle?: string;
  benefitsIntro?: string;
  benefits?: Array<
    {
      _key: string;
    } & Benefit
  >;
  order?: number;
  seo?: Seo;
  sourceUrl?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  body?: BlockContent;
  testimonial?: Testimonial;
  sector?: string;
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  websiteUrl?: string;
  services?: Array<string>;
  tools?: Array<
    {
      _key: string;
    } & ToolReference
  >;
  team?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  order?: number;
  coverImage?: ImageWithAlt;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  showcase?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  seo?: Seo;
  sourceUrl?: string;
};

export type Table = {
  _type: "table";
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | Benefit
  | Testimonial
  | Metric
  | ImageWithAlt
  | BlockContent
  | TeamMember
  | SanityImageCrop
  | SanityImageHotspot
  | TranslationMetadata
  | InternationalizedArrayReference
  | ProjectReference
  | ToolReference
  | InsightReference
  | InternationalizedArrayReferenceValue
  | Insight
  | Tool
  | Slug
  | TeamMemberReference
  | Project
  | Table
  | TableRow
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../src/sanity/queries.ts
// Variable: PROJECTS_INDEX_QUERY
// Query: *[_type == "project" && language == $lang && defined(slug.current)]    | order(coalesce(order, 999) asc, title asc) {   _id,  title,  "slug": slug.current,  sector,  summary,  services,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } }
export type PROJECTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  sector: string | null;
  summary: string | null;
  services: Array<string> | null;
  coverImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../../src/sanity/queries.ts
// Variable: PROJECT_DETAIL_QUERY
// Query: *[_type == "project" && language == $lang && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  sector,  summary,  services,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    body[]{ ..., _type == "image" => { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    metrics[]{ _key, value, label },    websiteUrl,    logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    gallery[]{ _key, ...{ alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    showcase[]{ _key, ...{ alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    testimonial { quote, name, role, photo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    tools[]->{ _id, title, "slug": slug.current, logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    team[]->{ _id, name, role, photo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    seo { title, description, image { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{  "language": language,  "slug": value->slug.current},    "related": *[_type == "project" && language == $lang && defined(slug.current) && slug.current != $slug]      | order(coalesce(order, 999) asc)[0...3] {   _id,  title,  "slug": slug.current,  sector,  summary,  services,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } }  }
export type PROJECT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  sector: string | null;
  summary: string | null;
  services: Array<string> | null;
  coverImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
  > | null;
  metrics: Array<{
    _key: string;
    value: string | null;
    label: string | null;
  }> | null;
  websiteUrl: string | null;
  logo: {
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  gallery: Array<{
    _key: string;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  showcase: Array<{
    _key: string;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  testimonial: {
    quote: string | null;
    name: string | null;
    role: string | null;
    photo: {
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  tools: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    logo: {
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  team: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    photo: {
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  translations: Array<{
    language: string | null;
    slug: string | null;
  }> | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    sector: string | null;
    summary: string | null;
    services: Array<string> | null;
    coverImage: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: ../../src/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && language == $lang && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../../src/sanity/queries.ts
// Variable: TOOLS_INDEX_QUERY
// Query: *[_type == "tool" && language == $lang && defined(slug.current)]    | order(coalesce(order, 999) asc, title asc) {   _id,  title,  "slug": slug.current,  intro,  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } }
export type TOOLS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  intro: string | null;
  logo: {
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../../src/sanity/queries.ts
// Variable: TOOL_DETAIL_QUERY
// Query: *[_type == "tool" && language == $lang && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  intro,  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },    benefitsTitle,    benefitsIntro,    benefits[]{ _key, title, text },    seo { title, description },    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{  "language": language,  "slug": value->slug.current},    "projects": *[_type == "project" && language == $lang && references(^._id)]      | order(coalesce(order, 999) asc) {   _id,  title,  "slug": slug.current,  sector,  summary,  services,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    "others": *[_type == "tool" && language == $lang && defined(slug.current) && slug.current != $slug]      | order(coalesce(order, 999) asc)[0...8] {   _id,  title,  "slug": slug.current,  intro,  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } }  }
export type TOOL_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  intro: string | null;
  logo: {
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  benefitsTitle: string | null;
  benefitsIntro: string | null;
  benefits: Array<{
    _key: string;
    title: string | null;
    text: string | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  translations: Array<{
    language: string | null;
    slug: string | null;
  }> | null;
  projects: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    sector: string | null;
    summary: string | null;
    services: Array<string> | null;
    coverImage: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
  others: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    intro: string | null;
    logo: {
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
  }>;
} | null;

// Source: ../../src/sanity/queries.ts
// Variable: TOOL_SLUGS_QUERY
// Query: *[_type == "tool" && language == $lang && defined(slug.current)].slug.current
export type TOOL_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../../src/sanity/queries.ts
// Variable: INSIGHTS_INDEX_QUERY
// Query: *[_type == "insight" && language == $lang && defined(slug.current)]    | order(publishedAt desc) {   _id,  title,  "slug": slug.current,  excerpt,  categories,  publishedAt,  author,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "minutes": round(length(string::split(pt::text(body), " ")) / 220) }
export type INSIGHTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  categories: Array<string> | null;
  publishedAt: string | null;
  author: string | null;
  coverImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  minutes: number;
}>;

// Source: ../../src/sanity/queries.ts
// Variable: INSIGHT_DETAIL_QUERY
// Query: *[_type == "insight" && language == $lang && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  categories,  publishedAt,  author,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "minutes": round(length(string::split(pt::text(body), " ")) / 220),    body[]{ ..., _type == "image" => { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },    seo { title, description },    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{  "language": language,  "slug": value->slug.current},    "related": *[_type == "insight" && language == $lang && defined(slug.current) && slug.current != $slug]      | order(publishedAt desc)[0...2] {   _id,  title,  "slug": slug.current,  excerpt,  categories,  publishedAt,  author,  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },  "minutes": round(length(string::split(pt::text(body), " ")) / 220) }  }
export type INSIGHT_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  categories: Array<string> | null;
  publishedAt: string | null;
  author: string | null;
  coverImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  minutes: number;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "table";
        rows?: Array<
          {
            _key: string;
          } & TableRow
        >;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  translations: Array<{
    language: string | null;
    slug: string | null;
  }> | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    categories: Array<string> | null;
    publishedAt: string | null;
    author: string | null;
    coverImage: {
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
    } | null;
    minutes: number;
  }>;
} | null;

// Source: ../../src/sanity/queries.ts
// Variable: INSIGHT_SLUGS_QUERY
// Query: *[_type == "insight" && language == $lang && defined(slug.current)].slug.current
export type INSIGHT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../../src/sanity/queries.ts
// Variable: SLUG_LOOKUP_QUERY
// Query: *[_type == $type && slug.current == $slug][0]{    language,    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{  "language": language,  "slug": value->slug.current}  }
export type SLUG_LOOKUP_QUERY_RESULT =
  | {
      language: null;
      translations: Array<{
        language: string | null;
        slug: string | null;
      }> | null;
    }
  | {
      language: string | null;
      translations: Array<{
        language: string | null;
        slug: string | null;
      }> | null;
    }
  | null;

// Source: ../../src/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type in ["project", "tool", "insight"] && defined(slug.current) && defined(language)]{    _type,    language,    "slug": slug.current,    _updatedAt  }
export type SITEMAP_QUERY_RESULT = Array<
  | {
      _type: "insight";
      language: string | null;
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _type: "project";
      language: string | null;
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _type: "tool";
      language: string | null;
      slug: string | null;
      _updatedAt: string;
    }
>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "project" && language == $lang && defined(slug.current)]\n    | order(coalesce(order, 999) asc, title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  sector,\n  summary,\n  services,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n }\n': PROJECTS_INDEX_QUERY_RESULT;
    '\n  *[_type == "project" && language == $lang && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  sector,\n  summary,\n  services,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n,\n    body[]{ ..., _type == "image" => { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    metrics[]{ _key, value, label },\n    websiteUrl,\n    logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n    gallery[]{ _key, ...{ alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    showcase[]{ _key, ...{ alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    testimonial { quote, name, role, photo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    tools[]->{ _id, title, "slug": slug.current, logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    team[]->{ _id, name, role, photo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    seo { title, description, image { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n  "language": language,\n  "slug": value->slug.current\n},\n    "related": *[_type == "project" && language == $lang && defined(slug.current) && slug.current != $slug]\n      | order(coalesce(order, 999) asc)[0...3] { \n  _id,\n  title,\n  "slug": slug.current,\n  sector,\n  summary,\n  services,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n }\n  }\n': PROJECT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "project" && language == $lang && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "tool" && language == $lang && defined(slug.current)]\n    | order(coalesce(order, 999) asc, title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  intro,\n  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n }\n': TOOLS_INDEX_QUERY_RESULT;
    '\n  *[_type == "tool" && language == $lang && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  intro,\n  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n,\n    benefitsTitle,\n    benefitsIntro,\n    benefits[]{ _key, title, text },\n    seo { title, description },\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n  "language": language,\n  "slug": value->slug.current\n},\n    "projects": *[_type == "project" && language == $lang && references(^._id)]\n      | order(coalesce(order, 999) asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  sector,\n  summary,\n  services,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n },\n    "others": *[_type == "tool" && language == $lang && defined(slug.current) && slug.current != $slug]\n      | order(coalesce(order, 999) asc)[0...8] { \n  _id,\n  title,\n  "slug": slug.current,\n  intro,\n  logo { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } }\n }\n  }\n': TOOL_DETAIL_QUERY_RESULT;
    '\n  *[_type == "tool" && language == $lang && defined(slug.current)].slug.current\n': TOOL_SLUGS_QUERY_RESULT;
    '\n  *[_type == "insight" && language == $lang && defined(slug.current)]\n    | order(publishedAt desc) { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  categories,\n  publishedAt,\n  author,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n  "minutes": round(length(string::split(pt::text(body), " ")) / 220)\n }\n': INSIGHTS_INDEX_QUERY_RESULT;
    '\n  *[_type == "insight" && language == $lang && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  categories,\n  publishedAt,\n  author,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n  "minutes": round(length(string::split(pt::text(body), " ")) / 220)\n,\n    body[]{ ..., _type == "image" => { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } } },\n    seo { title, description },\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n  "language": language,\n  "slug": value->slug.current\n},\n    "related": *[_type == "insight" && language == $lang && defined(slug.current) && slug.current != $slug]\n      | order(publishedAt desc)[0...2] { \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  categories,\n  publishedAt,\n  author,\n  coverImage { alt, hotspot, crop, asset->{ _id, url, metadata { lqip, dimensions { width, height } } } },\n  "minutes": round(length(string::split(pt::text(body), " ")) / 220)\n }\n  }\n': INSIGHT_DETAIL_QUERY_RESULT;
    '\n  *[_type == "insight" && language == $lang && defined(slug.current)].slug.current\n': INSIGHT_SLUGS_QUERY_RESULT;
    '\n  *[_type == $type && slug.current == $slug][0]{\n    language,\n    "translations": *[_type == "translation.metadata" && references(^._id)][0].translations[]{\n  "language": language,\n  "slug": value->slug.current\n}\n  }\n': SLUG_LOOKUP_QUERY_RESULT;
    '\n  *[_type in ["project", "tool", "insight"] && defined(slug.current) && defined(language)]{\n    _type,\n    language,\n    "slug": slug.current,\n    _updatedAt\n  }\n': SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
